wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    t:
      3:
      - 2
      4: 3.9.7
      5: 0.10.31
      8:
      - 5
artifact_description:
  desc: null
  value: 'Dataset metadata and .dvc file: This is an artfact for data information
    and not the data itself'
artifact_name:
  desc: null
  value: data.dvc
artifact_type:
  desc: null
  value: dataset_dvc_file
data_path:
  desc: null
  value: ./data
data_url:
  desc: null
  value: https://drive.google.com/file/d/1CSRquWi7xNYH9oSsVfZDtep2sCNauLQL/view?usp=sharing
download_new:
  desc: null
  value: true
repo:
  desc: null
  value: https://github.com/Sudonuma/sheldon.git
version:
  desc: null
  value: 971b6cae3f36007ea3df3e0c43c8a139ae6a9dbd
